#!/bin/bash

# dotfiles symlink script
dotfiles_dir=`pwd`


# bash

ln -sfn ${dotfiles_dir}/bash_profile ~/.bash_profile
ln -sfn ${dotfiles_dir}/bashrc ~/.bashrc
ln -sfn ${dotfiles_dir}/aliases ~/.aliases

# Vim

ln -sfn ${dotfiles_dir}/vimrc ~/.vimrc
ln -sfn ${dotfiles_dir}/.vim ~/.vim

# tmux
ln -sfn ${dotfiles_dir}/tmux.conf ~/.tmux.conf
